### ISSUE TITLE
Doesn't load when used in mods folder of a client.

### ISSUE THREAD

**Issue by CodeF53** [Wesley1808/ServerCore-Fabric#4]
**Describe the bug**
Despite the mod being in the mods folder of multimc, it doesn't get loaded.

**Reproduce**
Put the mod in any fabric 1.17 client, and launch

**Expected behavior**
It to load

**Reason why this is important**
While this mod is serversided, it would be helpful for improving performance in singleplayer worlds.

In particular, there is no other way to get villager lobotomizing and dynamic render distance in fabric other than this mod.

**Comment by Wesley1808** [comment]
Whilst this mod is mostly targeted at dedicated servers where Lithium alone isn't enough, I do understand your point.

Some of the patches in this mod are inherently incompatible with singleplayer / internal servers, with a few patches where singleplayer worlds use different algorithms, such as for entity ticking.
That is why, until now at least, it only runs on dedicated servers.

I'll look into this later this week to see if I can make most of these patches compatible with singleplayer worlds.

**Comment by Wesley1808** [comment]
This turned out to be much easier than I initially thought.
I'll backport these changes to 1.17 once I get around to test them some more, so nothing suddenly breaks.
