### ISSUE TITLE
Bed respawn point not set 

### ISSUE THREAD

**Issue by Soochaehwa** [Wesley1808/ServerCore-Fabric#7]
**Describe the bug**
Even if you set a respawn point on the bed, if you die, it will be go to the world spawn point

**Reproduce**

1. Set the respawn point on the bed
2. Move far away so that the chunk with the bed is unloaded
3. Die

**Versions** -Latest is not a version!
ServerCore: servercore-1.2.5-1.18
Minecraft: 1.18

**Mod incompatibilities**
I tested it using only the fabric api and server core

**Comment by Wesley1808** [comment]
Thank you for reporting this issue.
I've updated both CurseForge and Modrinth .jars with the fix for it (no new release).

**Comment by Xastabus** [comment]
Still experiencing this issue on 1.2.5-1.18

**Comment by Wesley1808** [comment]
I'm aware of that. I fixed it for a specific situation but then it reappeared in another.
Its fixed in the newest commit, which you can download from [here](https://github.com/Wesley1808/ServerCore-Fabric/actions/runs/1553511218).
