### ISSUE TITLE
non-player entities traveling from the end to the overworld fall into the void

### ISSUE THREAD

**Issue by CodeF53** [Wesley1808/ServerCore-Fabric#8]
**Describe the bug**
When any entity travels through the end portal (inside the end), the expected functionality is for it to land somewhere within the spawn chunks.

**Reproduce**
Drop sand into the end->overworld portal of a superflat glass world

**Expected behavior:**
Drop sand in portal, sand falls ontop of the terrain given.

**Actual behavior:**
drop sand in portal, sand falls into void

Note: once the spawn chunks are loaded, this is no longer a problem, so with larger chunks of sand this does not appear to be an issue

**Versions**
ServerCore: 1.2.5 - 1.18
Minecraft: 1.18

This is pretty severe as it lead to my server losing the dragon egg, and some of their horses when coming home victorious from the end.

**Comment by CodeF53** [comment]
Behavior is the same with servercore 1.2.4 - 1.18

**Comment by Wesley1808** [comment]
Did you try downloading the "new" 1.2.5-1.18 version?
I updated it to fix #7 , which is pretty likely to be the same issue.

**Comment by CodeF53** [comment]
I downloaded the new mod versions day of writing this issue.

**Comment by Wesley1808** [comment]
Commit https://github.com/Wesley1808/ServerCore-Fabric/commit/47fbe547570ceb7dbc284bf9f92a1f7c3b2b211c should resolve this issue, and many potential others regarding respawning, end portals, etc.
